// ESLint looks for a flat config at the project root only; the real config is generated by
// @nuxt/eslint into the build directory, so this file hands it over.
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt({
  rules: {
    // Size limits: lines under 120 characters, files under 500 lines, Vue template blocks
    // under 250 lines.
    '@stylistic/max-len': ['error', {
      code: 120,
      ignoreUrls: true,
    }],
    'max-lines': ['error', {
      max: 500,
      skipBlankLines: false,
      skipComments: false,
    }],
    'vue/max-lines-per-block': ['error', {
      template: 250,
    }],
  },
})
